/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import proyecto.Inventario;
import proyecto.Producto;
import vista.SeleccionMercado;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class RegistrarProductos extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    private proyecto.Inventario I1;
    private final String ARCHIVO_DATOS;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarProductos.class.getName());

    /**
     * Creates new form RegistrarProductos
     */
    public RegistrarProductos(
            java.awt.Frame parent,
            boolean modal,
            String archivoDatos) {
        super(parent, modal);
        initComponents();
        this.ARCHIVO_DATOS = archivoDatos;
        I1 = proyecto.Inventario.recuperarDatos(ARCHIVO_DATOS);
        if (I1 == null) {
            I1 = new proyecto.Inventario(0, "lunes");
        }
        actualizarTabla();
    }

    public void actualizarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TablaProductos.getModel();
        modelo.setRowCount(0);
        if (I1 != null && I1.getP() != null) {
            for (int i = 0; i < I1.getCantProd(); i++) {
                proyecto.Producto prod = I1.getP()[i];
                if (prod != null && !prod.getNombre().equals("")) {
                    Object[] fila = new Object[5];
                    fila[0] = (i + 1);
                    fila[1] = prod.getNombre();
                    fila[2] = prod.getCantidad();
                    fila[3] = prod.getPrecio() + " Bs";
                    fila[4] = prod.getLugarOrigen();

                    modelo.addRow(fila);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btGUARDAR = new javax.swing.JButton();
        btCERRAR = new javax.swing.JButton();
        btACTUALIZAR = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtNOMBRE = new javax.swing.JTextField();
        txtORIGEN = new javax.swing.JTextField();
        txtPRECIO = new javax.swing.JTextField();
        txtCANTIDAD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        ELIMINAR = new javax.swing.JButton();
        LISTA = new javax.swing.JButton();
        valor = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N

        btGUARDAR.setBackground(new java.awt.Color(255, 255, 153));
        btGUARDAR.setText("Guardar");
        btGUARDAR.addActionListener(this::btGUARDARActionPerformed);

        btCERRAR.setBackground(new java.awt.Color(255, 255, 204));
        btCERRAR.setText("Cerrar");
        btCERRAR.addActionListener(this::btCERRARActionPerformed);

        btACTUALIZAR.setBackground(new java.awt.Color(255, 255, 153));
        btACTUALIZAR.setText("Actualizar");
        btACTUALIZAR.addActionListener(this::btACTUALIZARActionPerformed);

        txtID.setBackground(new java.awt.Color(51, 102, 0));
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtNOMBRE.setBackground(new java.awt.Color(51, 102, 0));
        txtNOMBRE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtORIGEN.setBackground(new java.awt.Color(51, 102, 0));
        txtORIGEN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dia De Venta (martes/viernes)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        txtORIGEN.addActionListener(this::txtORIGENActionPerformed);

        txtPRECIO.setBackground(new java.awt.Color(51, 102, 0));
        txtPRECIO.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio por Unidad"));

        txtCANTIDAD.setBackground(new java.awt.Color(51, 102, 0));
        txtCANTIDAD.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btGUARDAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btACTUALIZAR)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtORIGEN, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPRECIO, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCANTIDAD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNOMBRE)
                    .addComponent(txtID))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btCERRAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(txtCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtORIGEN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGUARDAR)
                            .addComponent(btACTUALIZAR))
                        .addGap(11, 11, 11)))
                .addComponent(btCERRAR)
                .addGap(31, 31, 31))
        );

        TablaProductos.setBackground(new java.awt.Color(153, 153, 0));
        TablaProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 3));
        TablaProductos.setForeground(new java.awt.Color(0, 51, 0));
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE PRODUCTO", "CANDIDAD", "PRECIO", "DIA VENTA"
            }
        ));
        TablaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(TablaProductos);

        ELIMINAR.setBackground(new java.awt.Color(102, 0, 0));
        ELIMINAR.setForeground(new java.awt.Color(204, 51, 0));
        ELIMINAR.setText("Eliminar Inventario");
        ELIMINAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0)));
        ELIMINAR.addActionListener(this::ELIMINARActionPerformed);

        LISTA.setBackground(new java.awt.Color(255, 255, 204));
        LISTA.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        LISTA.setText("Listar Por Dia");
        LISTA.addActionListener(this::LISTAActionPerformed);

        valor.setBackground(new java.awt.Color(255, 255, 204));
        valor.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        valor.setText("Valor Total Inv.");
        valor.addActionListener(this::valorActionPerformed);

        buscar.setBackground(new java.awt.Color(255, 255, 204));
        buscar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        buscar.setText("Buscar Producto");
        buscar.addActionListener(this::buscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ELIMINAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ELIMINAR)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>                        

    private void btGUARDARActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            String nombre = txtNOMBRE.getText();
            int cantidad = Integer.parseInt(txtCANTIDAD.getText());
            float precio = Float.parseFloat(txtPRECIO.getText());

            String diaVenta = txtORIGEN.getText();

            proyecto.Producto nuevo = new proyecto.Producto(nombre, "Orgánico", diaVenta, precio, cantidad);

            I1.agregarProducto(nuevo);
            I1.persistirDatos(ARCHIVO_DATOS);
            actualizarTabla();

            txtID.setText("");
            txtNOMBRE.setText("");
            txtCANTIDAD.setText("");
            txtPRECIO.setText("");
            txtORIGEN.setText("");

            javax.swing.JOptionPane.showMessageDialog(this, "Producto registrado para el día " + diaVenta + " con éxito");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Revisa los datos ingresados.");
        }
    }                                         

    private void btCERRARActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Desea salir de esta ventana?",
                "Confirmar",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            dispose();
            SeleccionMercado ventana = new SeleccionMercado();
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
        }
    }                                        

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int filaSeleccionada = TablaProductos.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor selecciona un producto de la tabla para eliminar");
            return;
        }
        String nombreProducto = TablaProductos.getValueAt(filaSeleccionada, 1).toString();
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Estás segura de eliminar " + nombreProducto + " del BioMarket?", "Confirmar Eliminación", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            I1.quitarProducto(nombreProducto);
            I1.persistirDatos(ARCHIVO_DATOS);
            actualizarTabla();
            javax.swing.JOptionPane.showMessageDialog(this, "Producto eliminado y actualizado en el archivo");
        }
    }                                        

    private void btACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {                                             
        actualizarTabla();

        // 2. Limpiamos todas tus cajitas verdes para que queden listas para el siguiente producto
        txtID.setText("");
        txtNOMBRE.setText("");
        txtCANTIDAD.setText("");
        txtPRECIO.setText("");
        txtORIGEN.setText("");
        javax.swing.JOptionPane.showMessageDialog(this, "interfaz actualizada con exito");
    }                                            

    private void txtORIGENActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void LISTAActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String reporteFinal = "=== PRODUCTOS INSCRITOS POR DIA DE VENTA ===\n\n";

        if (I1 != null) {
            System.out.println("=======================================");
            I1.listarPorDia("Martes");
            reporteFinal += "MÁRTES:\n";
            boolean hayMartes = false;
            for (int i = 0; i < I1.getCantProd(); i++) {
                proyecto.Producto prod = I1.getP()[i];
                if (prod != null && prod.getLugarOrigen().equalsIgnoreCase("Martes") && !prod.getNombre().equals("")) {
                    reporteFinal += " - " + prod.getNombre() + " -> Stock: " + prod.getCantidad() + " | Precio: " + prod.getPrecio() + " Bs\n";
                    hayMartes = true;
                }
            }
            if (!hayMartes) {
                reporteFinal += "   (No hay productos registrados para el Martes)\n";
            }
            reporteFinal += "\n----------------------------------------------------------------------\n";
            System.out.println("---------------------------------------");
            I1.listarPorDia("Viernes");
            reporteFinal += "VIERNES:\n";
            boolean hayViernes = false;
            for (int i = 0; i < I1.getCantProd(); i++) {
                proyecto.Producto prod = I1.getP()[i];
                if (prod != null && prod.getLugarOrigen().equalsIgnoreCase("Viernes") && !prod.getNombre().equals("")) {
                    reporteFinal += " - " + prod.getNombre() + " -> Stock: " + prod.getCantidad() + " | Precio: " + prod.getPrecio() + " Bs\n";
                    hayViernes = true;
                }
            }
            if (!hayViernes) {
                reporteFinal += "   (No hay productos registrados para el Viernes)\n";
            }
            javax.swing.JTextArea areaTexto = new javax.swing.JTextArea(reporteFinal);
            areaTexto.setEditable(false);
            javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(areaTexto);
            scroll.setPreferredSize(new java.awt.Dimension(400, 300));
            javax.swing.JOptionPane.showMessageDialog(this, scroll, "Reporte de Inventario Detallado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            System.out.println("=======================================\n");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "El inventario está completamente vacío.");
        }
    }                                     

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        float total = I1.calcularValorInventario();
        javax.swing.JOptionPane.showMessageDialog(
                this,
                String.format("Valor total del inventario disponible:\n%.2f Bs", total),
                "Reporte de Inventario",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }                                     

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre del producto:"
        );
        if (I1.buscarProducto(nombre)) {
            JOptionPane.showMessageDialog(
                    this,
                    "El producto sí existe en el inventario."
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "El producto NO existe en el inventario."
            );
        }
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistrarProductos dialog
                        = new RegistrarProductos(new javax.swing.JFrame(), true, "datos_biomarket.dat");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton LISTA;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btACTUALIZAR;
    private javax.swing.JButton btCERRAR;
    private javax.swing.JButton btGUARDAR;
    private javax.swing.JButton buscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCANTIDAD;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtORIGEN;
    private javax.swing.JTextField txtPRECIO;
    private javax.swing.JButton valor;
    // End of variables declaration                   
}
