/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

/**
 *
 * @author HP
 */
public class RegistrarProductos extends javax.swing.JDialog {
    private proyecto.Inventario I1;
    private final String ARCHIVO_DATOS = "datos_biomarket.dat";
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarProductos.class.getName());

    /**
     * Creates new form RegistrarProductos
     */
    public RegistrarProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // PEGA ESTO AQUÍ ADENTRO:
        I1 = proyecto.Inventario.recuperarDatos(ARCHIVO_DATOS);
        if (I1 == null) {
            I1 = new proyecto.Inventario(0, "Lunes");
        }
        actualizarTabla();
    }
    public void actualizarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TablaProductos.getModel();
        modelo.setRowCount(0);
        if (I1 != null && I1.getP() != null) {
            for (int i = 0; i < I1.getCantProd(); i++) {
                proyecto.Producto prod = I1.getP()[i];
                if (prod != null && !prod.getNombre().equals("")) {
                    Object[] fila = new Object[4];
                    fila[0] = (i + 1);                  
                    fila[1] = prod.getNombre();        
                    fila[2] = prod.getCantidad();    
                    fila[3] = prod.getPrecio() + " Bs"; 

                    modelo.addRow(fila);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btGUARDAR = new javax.swing.JButton();
        btCERRAR = new javax.swing.JButton();
        btACTUALIZAR = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtNOMBRE = new javax.swing.JTextField();
        txtORIGEN = new javax.swing.JTextField();
        txtPRECIO = new javax.swing.JTextField();
        txtCANTIDAD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        btGUARDAR.setBackground(new java.awt.Color(255, 255, 153));
        btGUARDAR.setText("Guardar");
        btGUARDAR.addActionListener(this::btGUARDARActionPerformed);

        btCERRAR.setBackground(new java.awt.Color(255, 255, 204));
        btCERRAR.setText("Cerrar");
        btCERRAR.addActionListener(this::btCERRARActionPerformed);

        btACTUALIZAR.setBackground(new java.awt.Color(255, 255, 153));
        btACTUALIZAR.setText("Actualizar");

        txtID.setBackground(new java.awt.Color(51, 102, 0));
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtNOMBRE.setBackground(new java.awt.Color(51, 102, 0));
        txtNOMBRE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtORIGEN.setBackground(new java.awt.Color(51, 102, 0));
        txtORIGEN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Origen", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtPRECIO.setBackground(new java.awt.Color(51, 102, 0));
        txtPRECIO.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio por Unidad"));

        txtCANTIDAD.setBackground(new java.awt.Color(51, 102, 0));
        txtCANTIDAD.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btCERRAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btGUARDAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btACTUALIZAR)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtORIGEN, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPRECIO, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCANTIDAD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNOMBRE)
                    .addComponent(txtID))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(txtCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtORIGEN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGUARDAR)
                    .addComponent(btACTUALIZAR))
                .addGap(18, 18, 18)
                .addComponent(btCERRAR)
                .addGap(41, 41, 41))
        );

        TablaProductos.setBackground(new java.awt.Color(153, 153, 0));
        TablaProductos.setForeground(new java.awt.Color(0, 51, 0));
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGUARDARActionPerformed
        try {
            String nombre = txtNOMBRE.getText();
            int cantidad = Integer.parseInt(txtCANTIDAD.getText());
            float precio = Float.parseFloat(txtPRECIO.getText());
            
            proyecto.Producto nuevo = new proyecto.Producto(nombre, "Orgánico", "Cota-Cota", precio, cantidad);
            I1.agregarProducto(nuevo);
            I1.persistirDatos(ARCHIVO_DATOS);

            actualizarTabla();
            txtID.setText("");
            txtNOMBRE.setText("");
            txtCANTIDAD.setText("");
            txtPRECIO.setText("");
            txtORIGEN.setText("");

            javax.swing.JOptionPane.showMessageDialog(this, "¡Producto guardado y persistido con éxito!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor revisa los datos ingresados.");
        }
    }//GEN-LAST:event_btGUARDARActionPerformed

    private void btCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCERRARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCERRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistrarProductos dialog = new RegistrarProductos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btACTUALIZAR;
    private javax.swing.JButton btCERRAR;
    private javax.swing.JButton btGUARDAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCANTIDAD;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtORIGEN;
    private javax.swing.JTextField txtPRECIO;
    // End of variables declaration//GEN-END:variables
}
